version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestbox
    environment:
      - PORT=${PORT}
    ports:
      - '3000:3000'
        #depends_on:
        #- db
    volumes:
      - ./src:/app/src
